from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableParallel
#through this yiu can excute parallel chains
model1=ChatOllama(model='llama3.2:1b')
model2=ChatOllama(model='llama3.2:1b')
prompt1=PromptTemplate(
 template='Generate Short simple summary from this following {text} im providing you',
 input_variables=['text']
)
prompt2=PromptTemplate(template='Generate Short Questions from this following {text} im providing you ',
 input_variables=['text']
)
prompt3=PromptTemplate(template='merage the summary notes and short questions into a single document \n {notes}and {quiz}',
 input_variables=['notes','quiz']
)
parser=StrOutputParser()
#dict bane ge dono ke paralleli chlae ga
parallel_chains=RunnableParallel({
 'notes':prompt1|model1|parser,
 'quiz':prompt2|model2|parser
})#two output nekl notes and quiz nekly 
#merge # yha w input huaje ge 
merge_chain=prompt3|model1|parser
# paraelel ke output  transfer huneg merge mein 
chain=parallel_chains|merge_chain
text=""" Cybersecurity is the practice of protecting computers, networks, software applications, digital systems, and sensitive information from unauthorized access, misuse, modification, disruption, or destruction. As organizations increasingly depend on technology, cybersecurity has become an important part of almost every business and institution. Banks, hospitals, universities, government organizations, software companies, and even small businesses store and process large amounts of digital information. Protecting this information is important because a security incident can result in financial losses, privacy violations, reputational damage, and interruption of important services.

One of the most common cybersecurity threats is phishing. Phishing is a social engineering technique in which an attacker attempts to trick a person into revealing sensitive information such as passwords, usernames, credit card details, or authentication codes. Phishing attacks are commonly delivered through emails, text messages, fake websites, or social media messages. An attacker may create a message that appears to come from a trusted organization and may ask the victim to click a link, download a file, or provide account information. Modern phishing attacks can be difficult to recognize because attackers often copy the logos, language, and design of legitimate organizations. Users can reduce the risk of phishing by carefully checking links, verifying unexpected requests, avoiding suspicious attachments, and using multi-factor authentication.

Malware is another major cybersecurity threat. The term malware refers to malicious software designed to damage systems, steal information, monitor users, or provide unauthorized access to computers. Different types of malware include viruses, worms, trojans, spyware, and ransomware. A virus can attach itself to legitimate files and spread when those files are executed. A worm can spread automatically across networks without requiring the user to manually execute an infected file. A trojan disguises itself as legitimate software and attempts to convince the user to install it. Spyware can secretly monitor user activity and collect information. Ransomware is particularly dangerous because it can encrypt files and prevent users or organizations from accessing their data until certain demands are made.

Ransomware attacks have become a significant concern for organizations because they can affect both data and business operations. In a typical ransomware incident, malicious software gains access to a system and encrypts important files. The organization may suddenly lose access to databases, documents, applications, and other resources. Attackers may then demand payment in exchange for a decryption key. Organizations can reduce the impact of ransomware by maintaining regular backups, keeping software updated, limiting unnecessary privileges, training employees, monitoring systems, and preparing an incident response plan. Backups should be protected so that attackers cannot easily modify or delete them during an attack.

Passwords are another important part of cybersecurity. Weak or reused passwords can make accounts easier to compromise. Users sometimes choose passwords based on easily guessed information such as names, birthdays, or common words. Attackers can use automated techniques to attempt many possible passwords. Credential stuffing is another technique in which attackers use stolen username and password combinations from one service to attempt access to accounts on other services. This is especially effective when users reuse the same password across multiple websites. Using long and unique passwords for different accounts can significantly reduce this risk. Password managers can help users create and store unique passwords without requiring them to remember every password.

Multi-factor authentication, commonly called MFA, provides an additional layer of security. Instead of relying only on a password, MFA requires another form of verification. This may include a code generated by an authentication application, a physical security key, or another approved verification method. If an attacker obtains a user's password, MFA can make it more difficult for the attacker to access the account. However, users should still be careful because attackers may attempt social engineering techniques to convince victims to approve fraudulent authentication requests.

Another important concept in cybersecurity is encryption. Encryption transforms readable information into a protected format so that unauthorized individuals cannot easily understand it. The original readable information is known as plaintext, while the transformed information is called ciphertext. A cryptographic key is used as part of the encryption and decryption process. Encryption can protect information stored on devices as well as information transmitted across networks. For example, secure communication protocols can help protect information exchanged between a user's browser and a website. Encryption is widely used in online banking, messaging applications, cloud services, and many other digital systems.

Network security focuses on protecting communication networks and the devices connected to them. Firewalls are commonly used as a security control that can monitor and filter network traffic according to defined rules. A firewall may block certain types of unwanted connections while allowing legitimate traffic to pass. Organizations may also use intrusion detection and intrusion prevention systems to identify suspicious network activity. Network segmentation is another useful technique. Instead of placing every system on one large network, an organization can divide its infrastructure into separate network segments. This can limit the movement of an attacker if one part of the network becomes compromised.

Software security is also essential because vulnerabilities in applications can provide attackers with opportunities to compromise systems. A vulnerability is a weakness that may be exploited to produce an unwanted security result. Software developers should follow secure development practices and test applications for security problems. Common application security issues can include improper input validation, insecure authentication, weak access controls, and exposure of sensitive information. Developers should validate user input, apply appropriate authorization checks, protect sensitive data, and keep dependencies updated. Security testing should be performed throughout the software development lifecycle rather than only after an application has been completed.

Access control is another fundamental cybersecurity principle. It determines which users or systems are allowed to access specific resources and what actions they are permitted to perform. The principle of least privilege states that users and applications should receive only the permissions necessary to perform their required tasks. For example, an employee who only needs to read a particular database should not automatically receive permission to delete or modify every record. Limiting privileges can reduce the damage caused by compromised accounts or malicious insiders.

Human behavior plays a major role in cybersecurity. Even advanced technical security controls can be weakened when users make unsafe decisions. Social engineering attacks take advantage of human psychology rather than relying only on technical vulnerabilities. Attackers may create a sense of urgency, fear, curiosity, or authority to persuade victims to perform an action. Security awareness training can teach employees how to identify suspicious messages, protect credentials, report incidents, and follow organizational security policies. Regular training and simulated exercises can help employees develop safer habits.

Security monitoring and logging are important for detecting suspicious activity. Systems can generate logs containing information about authentication attempts, network connections, application activity, and other events. Security teams can analyze these logs to identify unusual behavior. For example, repeated failed login attempts from an unfamiliar location may indicate a possible attack. Centralized logging can make it easier to investigate incidents because information from multiple systems can be analyzed together. Organizations may use security information and event management systems to collect and analyze security-related events.

Incident response is the process of preparing for, detecting, investigating, containing, and recovering from cybersecurity incidents. An organization should have a plan before an incident occurs. When suspicious activity is detected, security teams may first investigate the event to determine its scope and severity. They may then contain affected systems to prevent the incident from spreading. After containment, the organization can remove malicious components, restore affected systems, and verify that normal operations can safely resume. After an incident, organizations should review what happened and identify improvements that can reduce the chance of similar incidents in the future.

Data privacy is closely related to cybersecurity but is not exactly the same thing. Cybersecurity focuses on protecting systems and information from threats, while privacy is concerned with how personal information is collected, processed, stored, shared, and used. Organizations that collect personal data should consider what information they actually need and how it should be protected. Sensitive information should not be exposed unnecessarily. Strong access controls, encryption, secure storage, and appropriate data-handling policies can help protect personal information.

Cloud computing has also changed the cybersecurity landscape. Organizations can store applications and data using cloud platforms instead of maintaining all infrastructure themselves. Cloud services can provide scalability and flexibility, but they also introduce security responsibilities. Organizations must properly configure access controls, authentication, storage permissions, network settings, and monitoring. A misconfigured cloud storage service, for example, could unintentionally expose sensitive information. Security teams therefore need to understand both traditional infrastructure security and cloud security concepts.

Artificial intelligence is increasingly being used in cybersecurity. Machine learning systems can analyze large amounts of security data and help identify unusual patterns. AI-based systems may assist security teams in detecting suspicious network activity, classifying potentially malicious files, identifying phishing messages, and prioritizing security alerts. However, artificial intelligence can also be misused by attackers. Attackers may use automated tools to create more convincing phishing messages, discover weaknesses, or increase the speed of certain attacks. Therefore, organizations need to consider both the defensive benefits and potential risks of AI.

Cybersecurity is not a single product or technology. It is a continuous process involving people, processes, and technology. A strong cybersecurity strategy may include security policies, employee training, access control, encryption, secure software development, network protection, backups, monitoring, and incident response. Organizations should regularly review their security controls because threats and technologies continue to change. A security measure that is effective today may require improvement as new vulnerabilities and attack techniques appear.

Ultimately, effective cybersecurity depends on reducing risk rather than assuming that every attack can be prevented. Organizations should identify their most valuable systems and information, understand possible threats, determine vulnerabilities, and prioritize appropriate security controls. Regular security assessments, software updates, employee education, strong authentication, reliable backups, and effective monitoring can significantly improve an organization's ability to prevent and respond to cyber incidents. By treating cybersecurity as an ongoing responsibility rather than a one-time task, individuals and organizations can better protect their digital systems and information."""
result=chain.invoke({'text':text})
print(result)
#kya huga chain me jo text hn wo fill huga jkha blank space hnm text ka then prompt 1 and prpompt 2 is ready as cahin ka first step hn paralel prompt wha wo run huga us me phly prompt 1 run huwa and notes me ja ke store huwa same prompt 2 run huwa quiz m store huwa rem dono ka alfgh algh text mila na ke dono k output connect huwe ok then do output mily notes and quiz wo jake merge me gae as input wha se ans aaya prompt model parser 
